services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    networks:
      - app-network

  playwright:
    container_name: playwright
    image: mcr.microsoft.com/playwright:v1.50.1-noble
    command: [ "npx","-y", "playwright", "run-server",
               "--port",
               "3000", "--host", "0.0.0.0" ]
    ports:
      - "3000:3000"
    networks:
      - app-network

  postgres:
    container_name: postgresql
    image: postgres:15
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jobdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


volumes:
  pgdata: